# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']
future: true # Enable future posts (date > current date)


# Site Settings
title: "ResBaz Perth"
email: "perthresbaz@gmail.com"
description: "The Research Bazaar is a worldwide festival promoting the digital literacy emerging at the center of modern research."
baseurl: "/ResBazPerth2021"
url: "https://curtinic.github.io/"
permalink: "/blog/:title"
#googleAnalyticsTrackingId: "UA-43643469-5"
#googleAnalyticsSiteUrl: "gdg-x.github.io"
#siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Curtin University"
#organizerAlternateName: "Centre for eResearch"
organizerDescription: "Curtin University is proud to host ResBaz Perth 2021"
#organizerEmail: ""
organizerLogo: "/img/seo/organizer-logo.png"
#organizerLink: "https://www.eresearch.auckland.ac.nz"

# Head
metaKeywords: "event, resbaz, research, bazaar, resbas, rezbaz, curtin, eresearch"
twitterAccount: "@ResBaz"
#socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
#socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "mailto:perthresbaz@gmail.com"
#c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/sessions/", text: "Sessions"}
 - {permalink: "/cod/", text: "Code of Conduct"}
bottomNavigationLinks:
 - {link: "mailto:perthresbaz@gmail.com", text: "Contact us"}
rightNavigationButtons:
 - {link: "mailto:perthresbaz@gmail.com", text: "Contact us"}

# Hero Block
heroImage: "hero.jpg"
# heroTitle: "ResBaz : <typeout> "
heroTitle: "ResBaz : Perth "
# eventDate: ""
typeoutTextValues: '"Perth"'
typeoutFallback: "Perth"
heroButtons:
 - {link: "", text: "28 June - 2 July 2021"}

# About Block
aboutTitle: "About ResBaz Perth 2021: 'Pick and Mix' Edition"
aboutSubtitle: "Conference"
aboutText: "<p>The Research Bazaar is a worldwide festival promoting the digital literacy emerging at the center of modern research.</p>

<p>Hosted online in 2021, the Perth Research Bazaar is a <b>FREE</b> 5-day virtual 'pick and mix' conference where researchers come together to up-skill in ‘next generation digital research tools and skills’. In the spirit of a marketplace or bazaar, ResBaz is a highly participatory event where researchers from many different disciplines can learn, share knowledge and skills, and have fun!</p>

<p>Who should attend? Researchers at ALL levels from ALL disciplines. PhD and research Masters students are especially encouraged to attend. Research technologists who support researchers to do their job should also come along! Sessions at ResBaz this year are intended to offer a brief practical introduction to a broad selection of topics and tools related to digital research practice relevant across the disciplines.</p>

<p>Please note, <b>registration is required for each of the individual workshops</b>. You may attend as many workshops and presentations as you like! Some of the computational training workshops do have capacity limits, and we will endeavour to make recordings of these sessions available on the website where possible.</p>

<p>Registrations are now open for the majority of the sessions, please check the <a href=\"https://curtinic.github.io/ResBazPerth2021/schedule/\">SCHEDULE</a> and <a href=\"https://curtinic.github.io/ResBazPerth2021/sessions/\">SESSIONS</a> pages.</p>"


# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "20", specialCharacter: "+", info: "helpers", detail: ""}
 - {count: "40", specialCharacter: "+", info: "hours", detail: ""}
 - {count: "25", specialCharacter: "+", info: "speakers", detail: ""}
 - {count: "3", specialCharacter: "", info: "parallel streams", detail: ""}

# Latest News Block
latestNewsTitle: "Latest News"

# Rockstar Speakers Block
# rockstarSpeakersImage: "rockstar-speakers.jpg"
# rockstarSpeakersCount: 4
# rockstarSpeakersTitle: "Keystory speakers"
# rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Virtual event, hosted by Curtin University"
#eventLocationLink: "https://www.auckland.ac.nz/en/on-campus/our-campuses/landmarks-facilities/the-clocktower.html"
eventStreetAddress: "Kent St"
eventAddressLocality: "Bentley"
eventAddressLocalityRegion: "Perth"
eventPostalCode: "6102"
eventAddressCountry: "Australia"
eventStartTime: "2021-06-28T09:00"
eventDoorTime: "09:00"
eventEndTime: "2021-07-02T17:00"
#eventPlaceCoordinates: "-36.850223, 174.76922"
#mapCenterCoordinates: "-36.850223, 174.76922"
#mapMobileCenterCoordinates: "-36.850223, 174.76922"

# Venue Block
# venueBlockTitle: "Past Events"
# venueBigImage: "cam_beanbags.jpg"
# venueSmallImage2: "publishing_tabletop.jpg"
# venueSmallImage1: "sam_on_the_wall.jpg"
# venueSmallImage3: "speaker_beanbags.jpg"

# venueTitle: "ResBaz Perth 2019"
# venueFeatures: ["Recently refurbished lecture rooms.", "Free catering provided daily.", "Bean bags and areas for socializing!"]

# Tweets Feed Block
tweetsFeedImage: "pertheq.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "PerthResBaz"
twitterFeed: "https://twitter.com/ResBaz"

# Partners Block
organizersTitle: "Organisers"
# partnersTitle: "Partners"
# partnersC4sponsorsButton: "Become a supporter"
# partnersLink: ""

# Team Block
teamBlockTitle: "Volunteers"
teamSubtitle: "We'd like to thank the dedicated volunteers behind ResBaz Perth 2021!"
teamText: "<p><b>ResBaz Perth 2020/2021 Program Organising Committee</p></b>

<p> Curtin Institute for Computation, Curtin University | Kathryn Napier, Rebecca Lange <br>
Curtin University | Shih Ching Fu, Tania Lerch <br>
Australian Research Data Commons | Matthias Liffers, Nichola Burton <br>
Pawsey Supercomputing Centre | Ann Backhaus, Luke Edwards <br>
Edith Cowan University | Chandra Salgado Kent <br>
University of Western Australia | Katina Toufexis <br>
Edith Cowan University | Alyce Russell <br>
Rick Tankard</p>

<p><b> ResBaz Perth 2021 Helpers </p></b>
<p> Curtin Institute for Computation, Curtin University | Foad Farivar, Rebecca Lange, Dan Marrable, Kathryn Napier, Nancy Tippaya, Leigh Tyers<br>
Curtin University | Janice Chan, Shih Ching Fu, Tania Lerch, Valerie Maxville, Andrew Rohl, Ranjodh Singh, Michael Wilson <br>
Edith Cowan University | Alyce Russell<br>
Harry Perkins Institute | Joakim Karlsson<br>
Murdoch University | Siobhan Egan<br>
Pawsey Supercomputing Centre | Sarah Beecroft<br>
The University of Western Australia | Philipp Bayer, Brady Johnston, Lyron Winderbaum</p>"


# Subscribe Block
# subscribeImage: "subscribe.jpg"
# subscribeTitle: "Subscribe for updates"
# subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
# subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
# ticketsTitle: "Pricetable"
# ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
# ticketsOffers:
#  -
#   name: "Early Bird"
#   price: "350"
#   priceCurrency: "UAH"
#   ticketsNumber: "150"
#   ribbon: "-5%"
#   buyButtonLink: "http://dfua.ticketforevent.com/"
#   buyButtonText: "Buy Now"
#   ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#   validFrom: "2014-08-25T10:00"
#   validThrough: "2014-09-30T23:59"
#  -
#   name: "Last Chance"
#   price: "450"
#   priceCurrency: "UAH"
#   ticketsNumber: "100"
#   ribbon: "-20%"
#   featured: true
#   buyButtonLink: "http://dfua.ticketforevent.com/"
#   buyButtonText: "Buy Now"
#   ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#   validFrom: "2014-10-01T00:00"
#   validThrough: "2014-10-23T23:59"
#   disabled: true
#  -
#   name: "Student"
#   price: "200"
#   priceCurrency: "UAH"
#   ticketsNumber: "50"
#   buyButtonLink: "http://dfua.ticketforevent.com/"
#   buyButtonText: "Buy Now"
#   additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
#   ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#   validFrom: "2014-08-20T10:00"
#   validThrough: "2014-10-23T23:59"
#   soldOut: true
#   soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://twitter.com/ResBaz", icon: "twitter"}
# - {link: "https://resbaz.github.io/resbaz2021/perth/", icon: "site"}
 - {link: "mailto:perthresbaz@gmail.com", icon: "email"}
footerBlocks:
 -
  title: "Host"
  links:
   - {link: "https://www.curtin.edu.au", text: "Curtin University"}
  #  - {link: "https://www.ecu.edu.au", text: "Edith Cowan University"}
  #  - {link: "https://www.uwa.edu.au", text: "The University of Western Australia"}
  #  - {link: "https://www.notredame.edu.au/", text: "The University of Notre Dame Australia"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:perthresbaz@gmail.com", text: "perthresbaz@gmail.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
# discusShortName: "devfestua"

# Speakers List Block
showSessions: true



# Logistics Find Way Block
# findWayTitle: "Find your way here"
# findWayDistance: "Distance"
# findWayDriving: "DRIVING"
# findWayWalking: "WALKING"
# findWayBicycling: "BICYCLING"
# findWayTransit: "TRANSIT"
# findWayFindFlight: "Find Flight"
# logisticsMapCenterCoordinates: "49.056728, 3.117289"
# logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
# logisticsMapAutoDirections: false

# # Logistics Direction Details Block
# directionDetailsImage: "direction-details.jpg"
# directionDetailsTitle: "Get around Lviv"
# directionDetailsCards:
#  - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
#  - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
#  - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
# directionDetailsWideCards:
#  -
#   title: "Questions?"
#   subCards:
#    -
#     title: "Hotels"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#    -
#     title: "Registration"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#    -
#     title: "Attendance Details"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
