# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']
future: true # Enable future posts (date > current date)


# Site Settings
title: "ResBaz Perth"
email: "perthresbaz@gmail.com"
description: "The Research Bazaar is a worldwide festival promoting the digital literacy emerging at the center of modern research."
baseurl: "/ResBazPerth2022"
url: "https://curtinic.github.io/"
permalink: "/blog/:title"
#googleAnalyticsTrackingId: "UA-43643469-5"
#googleAnalyticsSiteUrl: "gdg-x.github.io"
#siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Curtin University"
#organizerAlternateName: "Centre for eResearch"
organizerDescription: "Curtin University is proud to host ResBaz Perth 2022"
#organizerEmail: ""
organizerLogo: "/img/seo/organizer-logo.png"
#organizerLink: "https://www.eresearch.auckland.ac.nz"

# Head
metaKeywords: "event, resbaz, research, bazaar, resbas, rezbaz, curtin, eresearch"
twitterAccount: "@ResBaz"
#socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
#socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "mailto:perthresbaz@gmail.com"
#c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/sessions/", text: "Sessions"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/cod/", text: "Code of Conduct"}
bottomNavigationLinks:
 - {link: "mailto:perthresbaz@gmail.com", text: "Contact us"}
rightNavigationButtons:
# - {link: "https://tinyurl.com/yt3zs9jv", text: "KEEP UPDATED"}
 - {link: "https://www.eventbrite.com.au/e/2022-perth-research-bazaar-resbaz-tickets-387265340057", text: "REGISTER NOW"}

# Hero Block
heroImage: "WADSIH_hero_1.png"
# heroTitle: "ResBaz : <typeout> "
heroTitle: "ResBaz : Perth "
# eventDate: ""
#typeoutTextValues: '"Perth"'
#typeoutFallback: "Perth"
heroButtons:
 - {link: "", text: "6 - 8 September 2022, Curtin Medical School, Curtin University"}

# About Block
aboutTitle: "About ResBaz Perth 2022"
aboutSubtitle: "Community, Conference and Campaign"
aboutText: "<p>The Research Bazaar (ResBaz) is a worldwide festival promoting the digital literacy emerging at the center of modern research.</p>

<p>Hosted in-person at Curtin University in 2022 by the WA Data Science Innovation Hub, the Perth Research Bazaar is <b>a low-cost 3-day</b> conference where researchers come together to up-skill in 'next generation digital research tools and skills'. In the spirit of a marketplace or bazaar, ResBaz is a highly participatory event where researchers from many different disciplines can learn, share knowledge and skills, and have fun!</p>
<p>Perth ResBaz 2022 is a combination of computational training workshops (such as introduction to version control, introduction to R, introduction to python), electives (shorter 45 to 90 minute tutorials), and community events. Networking and social sessions form an important component of ResBaz, bringing together all participants to meet and network and to hear from keynote speakers and panelists.</p>
<p>Who should attend? Researchers at ALL levels from ALL disciplines. PhD and research Masters students are especially encouraged to attend. Research technologists who support researchers to do their job should also come along! Sessions at ResBaz this year are intended to offer a brief practical introduction to a broad selection of topics and tools related to digital research practice relevant across the disciplines.</p>
<br>
<br>

<h2>Registrations</h2>
<br>
<h4>Ticket Price</h4>

<p>$100 (incl. GST) + BF. Tickets are limited to 100 participants.</p>

<br>
<h4>Ticket Inclusions</h4>

<p>Your ticket includes:</p>

<p>* 3 days of professional learning</p>
<p>* access to all sessions to keynotes, panels and training workshops</p>
<p>* a multitude of networking opportunities</p>
<p>* full-day catering, including morning/afternoon tea, and lunch</p>
<p>* plus sundowner drinks & canapés</p>

<p>NOTE: An email to register for the individual training sessions/streams will be sent towards the end of August 2022. </p>

<br>
<h4>First Release Tickets (19 July 2022)</h4>

<p>Reserved for participating sponsoring WA universities from 19 July.</p>

<p>Please request the relevant Access Code from your respective university graduate/higher degree research school or office.</p>

<br>
<h4>General Admission Release Tickets (early August 2022)</h4>

<p>Remaining tickets will go on sale to the general public early August, unless allocation previously exhausted. To be notified when General Admission tickets go on sale, please register your interest to <b><a href=\"https://docs.google.com/forms/d/e/1FAIpQLSco97dodkcNEHcpITX4U6-uY0vKj_ygUCh67h0-AwTJy47VtQ/viewform?fbzx=3552297580201525183\">KEEP UPDATED HERE</a></b></p>"

# Tickets Block
ticketsTitle: "Register Now"
ticketsInfo: "Tickets grant access to all sessions, keynotes, panels and training workshops."
ticketsOffers:
 -
  name: "ResBaz Perth 2022 Tickets"
  price: "100"
  priceCurrency: "AUD"
  ticketsNumber: "100"
  buyButtonLink: https://www.eventbrite.com.au/e/2022-perth-research-bazaar-resbaz-tickets-387265340057
  buyButtonText: "Register Now"

 
# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "20", specialCharacter: "+", info: "electives and workshops", detail: ""}
 #- {count: "40", specialCharacter: "+", info: "hours", detail: ""}
 - {count: "30", specialCharacter: "+", info: "speakers", detail: ""}
 - {count: "4", specialCharacter: "+", info: "parallel streams", detail: ""}
 - {count: "3", specialCharacter: "", info: "networking events", detail: ""}

# Latest News Block
latestNewsTitle: "Latest News"

# Rockstar Speakers Block
# rockstarSpeakersImage: "rockstar-speakers.jpg"
# rockstarSpeakersCount: 4
# rockstarSpeakersTitle: "Keystory speakers"
# rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "In-person event, hosted by the WA Data Science Innovation Hub at Curtin University, Building 410 (Curtin Medical School)"
# eventLocationLink: "https://use.mazemap.com/#v=1&config=curtinuniversity&zlevel=1&center=115.893444,-32.001906&zoom=16.9&campusid=296&sharepoitype=poi&sharepoi=1000462438"
eventStreetAddress: "Kent St"
eventAddressLocality: "Bentley"
eventAddressLocalityRegion: "Perth"
eventPostalCode: "6102"
eventAddressCountry: "Australia"
eventStartTime: "2022-09-06T09:00"
eventDoorTime: "09:00"
eventEndTime: "2022-09-08T17:00"
# eventPlaceCoordinates: "-32.00167, 115.89334"
# mapCenterCoordinates: "-32.00167, 115.89334"
# mapMobileCenterCoordinates: "-32.00167, 115.89334"

# Venue Block
venueBlockTitle: "Past Events"
venueBigImage: "cam_beanbags.jpg"
venueSmallImage2: "publishing_tabletop.jpg"
venueSmallImage1: "sam_on_the_wall.jpg"
venueSmallImage3: "speaker_beanbags.jpg"

# venueTitle: "ResBaz Perth 2019"
# venueFeatures: ["Recently refurbished lecture rooms.", "Free catering provided daily.", "Bean bags and areas for socializing!"]

# Tweets Feed Block
tweetsFeedImage: "pertheq.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "PerthResBaz"
twitterFeed: "https://twitter.com/ResBaz"

# Partners Block
organizersTitle: "Organisers"
organizersImage: "pertheq.jpg"
# partnersTitle: "Partners"
# partnersC4sponsorsButton: "Become a supporter"
# partnersLink: ""

# Team Block
teamBlockTitle: "Volunteers"
teamSubtitle: "We'd like to thank the dedicated volunteers behind Perth ResBaz 2022!"
teamText: "<p><b>Perth ResBaz 2022 Program Organising Committee</p></b>

<p> Curtin Institute for Computation, Curtin University | Jamiu Ekundayo, Kathryn Barker, Kathryn Napier <br>
Curtin University | Shih Ching Fu, Tania Lerch <br>
Minderoo Foundation | Philipp Bayer <br>
Murdoch University | Andrew Walsh <br>
Pawsey Supercomputing Centre | Ann Backhaus, Luke Edwards <br>
University of Western Australia | Dave Edwards, James Ward <br>
WA Data Science Innovation Hub | Shannon Hansen <br>
</p>

<p><b>Perth ResBaz Helpers and Volunteers</b></b></p>
<p>Curtin Institute for Computation, Curtin University | Joel Dunstan, Paul Hancock, Carlo Martinotti, Calvin Pang, Christian Proud, Nick Swainston, Trish Radotic <br>
Curtin University | Drew Fordham, Victor Olet, Ranjodh Singh, Molly Tebo <br>
Murdoch University | Siobhan Egan, Reika Masuda <br>
University of Western Australia | Chris Bording, Brady Johnston, Rose-anna Inglis <br>
WA Data Science Innovation Hub | Ivana Deng <br>
</p>"



# Subscribe Block
# subscribeImage: "subscribe.jpg"
# subscribeTitle: "Subscribe for updates"
# subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
# subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Footer
socialLinks:
 - {link: "https://twitter.com/ResBaz", icon: "twitter"}
# - {link: "https://resbaz.github.io/resbaz2022/perth/", icon: "site"}
 - {link: "mailto:perthresbaz@gmail.com", icon: "email"}
footerBlocks:

 -
  title: "Host"
  links:
   - {link: "https://www.curtin.edu.au", text: "Curtin University"}
   - {link: "https://wadsih.org.au/", text: "WA Data Science Innovation Hub"}
 -
  title: "Sponsors"
  links:
   - {link: "https://www.curtin.edu.au", text: "Curtin University"}
   #- {link: "http://www.delltechnologies.com", text: "Dell Technologies"}
   - {link: "https://murdoch.edu.au/", text: "Murdoch University"}
   - {link: "https://www.uwa.edu.au", text: "The University of Western Australia"}
   - {link: "https://www.notredame.edu.au/", text: "The University of Notre Dame Australia"}
   - {link: "https://wadsih.org.au/", text: "WA Data Science Innovation Hub"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:perthresbaz@gmail.com", text: "perthresbaz@gmail.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
# discusShortName: "devfestua"

# Speakers List Block
showSessions: true



# Logistics Find Way Block
# findWayTitle: "Find your way here"
# findWayDistance: "Distance"
# findWayDriving: "DRIVING"
# findWayWalking: "WALKING"
# findWayBicycling: "BICYCLING"
# findWayTransit: "TRANSIT"
# findWayFindFlight: "Find Flight"
# logisticsMapCenterCoordinates: "49.056728, 3.117289"
# logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
# logisticsMapAutoDirections: false

# # Logistics Direction Details Block
# directionDetailsImage: "direction-details.jpg"
# directionDetailsTitle: "Get around Lviv"
# directionDetailsCards:
#  - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
#  - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
#  - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
# directionDetailsWideCards:
#  -
#   title: "Questions?"
#   subCards:
#    -
#     title: "Hotels"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#    -
#     title: "Registration"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#    -
#     title: "Attendance Details"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
